#ifndef MENU_SCREEN_CONSTANTS_H
#define MENU_SCREEN_CONSTANTS_H
#include <Arduino.h>

const short SCREEN_MODE_HOME = 0;
const short SCREEN_MODE_PREDIT = 1;

const short SCREEN_WIDTH = 320;
const short SCREEN_HEIGHT = 240;
const short SCREEN_FONT_WIDTH = 6;
const short SCREEN_FONT_HEIGHT = 8;

const int MODE_SELECTOR_POS_X = 0;
const int MODE_SELECTOR_POS_Y = 0;
const int MODE_SELECTOR_WIDTH = 54;
const int MODE_SELECTOR_HEIGHT = 201;
const byte MODE_BUTTON_BLANK_PERCENT = 5;

const uint16_t MODE_SELECTOR_BACKGROUND = 0;       //BLACK
const uint16_t MODE_BUTTON_STANDARD_COLOR = 50712; //GREY
const uint16_t MODE_BUTTON_ACTIVE_COLOR = 34800;   //LIGHT GREEN
const uint16_t MODE_BUTTON_TEXT_COLOR = 128;       //DARK GREEN
const uint16_t MODE_BUTTON_EDGE_COLOR = 128;       //DARK GREEN

const int PRESET_SELECTOR_POS_X = 54;
const int PRESET_SELECTOR_POS_Y = 0;
const int PRESET_SELECTOR_WIDTH = 54 * 3;
const int PRESET_SELECTOR_HEIGHT = 101;
const byte PRESET_SELECTOR_TOP_PERCENT = 60;
const uint16_t PRESET_BUTTON_STANDARD_COLOR = 65504; //YELLOW
const uint16_t PRESET_BUTTON_ACTIVE_COLOR = 65535;   //WHITE
const uint16_t PRESET_BUTTON_TEXT_COLOR = 0;         //BLACK
const uint16_t PRESET_BUTTON_EDGE_COLOR = 0;         //BLACK

const int VOLUME_SLIDER_POS_X = 0;
const int VOLUME_SLIDER_POS_Y = 201;
const int VOLUME_SLIDER_WIDTH = 320;
const int VOLUME_SLIDER_HEIGHT = 39;
const uint16_t VOLUME_SLIDER_BACKGROUND_COLOR = 1171; //BLUE-GREEN
const uint16_t VOLUME_SLIDER_BOX_COLOR = 2016;        //GREEN
const int VOLUME_SLIDER_BOX_WIDTH = 42;

const int WORD_MODE_BUTTON_POS_X = 54;
const int WORD_MODE_BUTTON_WIDTH = 54;
const int ENTERTAINMENT_BUTTONS_HEIGHT = 50;
const int ENTERTAINMENT_BUTTONS_POS_Y = 100;
const int LIGHTS_MODE_BUTTON_WIDTH = 54;
const int LIGHTS_MODE_BUTTON_POS_X = 108;
const int MUSIC_MODE_BUTTON_WIDTH = 54;
const int MUSIC_MODE_BUTTON_POS_X = 162;
const int MUSIC_PLAYLIST_BUTTON_POS_X = 216;
const int MUSIC_PLAYLIST_BUTTON_WIDTH = 104;
const uint16_t ENTERTAINMENT_BUTTONS_COLOR = 52093;        //LIGHT PURPLE
const uint16_t ENTERTAINMENT_BUTTONS_ACTIVE_COLOR = 65535; //WHITE
const uint16_t ENTERTAINMENT_BUTTONS_TEXT_COLOR = 0;       //BLACK

const int SCREEN_PRESSED_THRESHOLD = 700;
const int SCREEN_MIN_X = 650;
const int SCREEN_MAX_X = 7300;
const int SCREEN_MIN_Y = 7600;
const int SCREEN_MAX_Y = 900;
const int SCREEN_DEBOUNCE_TIME = 20;

#endif
